In [39]:
import re
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
f = open(r"C:\Users\Akshit Joshi\Desktop\Whatsapp-chat-analysis\Chats\WhatsApp Chat with Ajay Virar.txt","r", encoding = 'utf-8')

In [3]:
data = f.read()
print(data)

3/21/24, 5:36 PM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
3/21/24, 5:36 PM - Akshit Joshi: <Media omitted>
5/3/24, 11:04 AM - Ajay Virar: <Media omitted>
5/3/24, 11:05 AM - Ajay Virar: Please send your resume on ajay.vyas1@gds.ey com
5/3/24, 11:06 AM - Akshit Joshi: Yes
5/3/24, 11:06 AM - Akshit Joshi: Okay
5/3/24, 11:06 AM - Ajay Virar: Good please send resume will refer
5/3/24, 11:07 AM - Akshit Joshi: Okay
5/3/24, 11:11 AM - Akshit Joshi: Address not found!
5/3/24, 11:12 AM - Akshit Joshi: Is it ajay.vyas1@gds.ey.com?
5/3/24, 11:12 AM - Ajay Virar: Yes
5/3/24, 11:12 AM - Akshit Joshi: Okay
5/3/24, 11:15 AM - Akshit Joshi: I have sent the mail
5/3/24, 11:22 AM - Ajay Virar: Received
5/3/24, 11:22 AM - Akshit Joshi: Okay
5/3/24, 11:23 AM - Ajay Virar: Will refer will use emailid and mobile number given in resume
5/3/24, 11:24 AM - Akshit Joshi: Okay
5/3/24, 11:24 AM - Akshit Joshi: Both are active
5/3/24, 11:37 AM - Ajay Virar: Ok
5/3/24, 12:12 PM - Ajay Virar: Did you received any email from ey
5/3/24, 12:12 PM - Ajay Virar: ?
5/3/24, 12:15 PM - Akshit Joshi: Yes
5/3/24, 12:19 PM - Akshit Joshi: I have given both of the concern
5/3/24, 12:41 PM - Ajay Virar: Ok
5/5/24, 2:20 PM - Ajay Virar: check JP morgan has some openings check if that works

https://sightsinplus.com/news/hiring/jpmorgan-chase-in-india-is-hiring-for-over-500-roles-apply-here/
5/5/24, 4:48 PM - Akshit Joshi: Okay
5/5/24, 4:53 PM - Akshit Joshi: I visited this but freshers mate Indian applicants mate nathi koi opportunity
5/5/24, 4:54 PM - Akshit Joshi: And any update regards to this?
5/5/24, 4:56 PM - Ajay Virar: Ok
5/5/24, 4:57 PM - Ajay Virar: I have applied if profile is matching than you will get call
5/5/24, 4:57 PM - Akshit Joshi: Okay
5/5/24, 4:57 PM - Akshit Joshi: Thanks ☺️

In [4]:
# pattern =  r'\d{1,2}/\d{1,2}/\d{2},\d{1,2}:\d{2}\s*(AM|PM)?\s*-\s*(.*?):\s*(.*)' pattern for whole 
# pattern = r"\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s*(AM|PM)?\s-\s" #pattern till date and time
# pattern =  r"\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s*(?:AM|PM)?\s*-\s[^-]+"
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s(?:AM|PM)?\s-\s'

In [5]:
message = re.split(pattern, data)[1:]
message

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 'Akshit Joshi: <Media omitted>\n',
 'Ajay Virar: <Media omitted>\n',
 'Ajay Virar: Please send your resume on ajay.vyas1@gds.ey com\n',
 'Akshit Joshi: Yes\n',
 'Akshit Joshi: Okay\n',
 'Ajay Virar: Good please send resume will refer\n',
 'Akshit Joshi: Okay\n',
 'Akshit Joshi: Address not found!\n',
 'Akshit Joshi: Is it ajay.vyas1@gds.ey.com?\n',
 'Ajay Virar: Yes\n',
 'Akshit Joshi: Okay\n',
 'Akshit Joshi: I have sent the mail\n',
 'Ajay Virar: Received\n',
 'Akshit Joshi: Okay\n',
 'Ajay Virar: Will refer will use emailid and mobile number given in resume\n',
 'Akshit Joshi: Okay\n',
 'Akshit Joshi: Both are active\n',
 'Ajay Virar: Ok\n',
 'Ajay Virar: Did you received any email from ey\n',
 'Ajay Virar: ?\n',
 'Akshit Joshi: Yes\n',
 'Akshit Joshi: I have given both of the concern\n',
 'Ajay Virar: Ok\n',
 'Ajay Virar: check JP morgan has some openings check if that works\n\nhttps://sightsinplus.com/news/hiring/jpmorgan-chase-in-india-is-hiring-for-over-500-roles-apply-here/\n',
 'Akshit Joshi: Okay\n',
 'Akshit Joshi: I visited this but freshers mate Indian applicants mate nathi koi opportunity\n',
 'Akshit Joshi: And any update regards to this?\n',
 'Ajay Virar: Ok\n',
 'Ajay Virar: I have applied if profile is matching than you will get call\n',
 'Akshit Joshi: Okay\n',
 'Akshit Joshi: Thanks ☺️\n']

In [6]:
dates = re.findall(pattern, data)

In [7]:
dates = [s.replace('\u202F', ' ')for s in dates] # we had to run this as '/s' in pattern caught non-breaking element "\u202f" need to be replace by space " "

In [8]:
dates

['3/21/24, 5:36 PM - ',
 '3/21/24, 5:36 PM - ',
 '5/3/24, 11:04 AM - ',
 '5/3/24, 11:05 AM - ',
 '5/3/24, 11:06 AM - ',
 '5/3/24, 11:06 AM - ',
 '5/3/24, 11:06 AM - ',
 '5/3/24, 11:07 AM - ',
 '5/3/24, 11:11 AM - ',
 '5/3/24, 11:12 AM - ',
 '5/3/24, 11:12 AM - ',
 '5/3/24, 11:12 AM - ',
 '5/3/24, 11:15 AM - ',
 '5/3/24, 11:22 AM - ',
 '5/3/24, 11:22 AM - ',
 '5/3/24, 11:23 AM - ',
 '5/3/24, 11:24 AM - ',
 '5/3/24, 11:24 AM - ',
 '5/3/24, 11:37 AM - ',
 '5/3/24, 12:12 PM - ',
 '5/3/24, 12:12 PM - ',
 '5/3/24, 12:15 PM - ',
 '5/3/24, 12:19 PM - ',
 '5/3/24, 12:41 PM - ',
 '5/5/24, 2:20 PM - ',
 '5/5/24, 4:48 PM - ',
 '5/5/24, 4:53 PM - ',
 '5/5/24, 4:54 PM - ',
 '5/5/24, 4:56 PM - ',
 '5/5/24, 4:57 PM - ',
 '5/5/24, 4:57 PM - ',
 '5/5/24, 4:57 PM - ']

In [9]:
df = pd.DataFrame({'user_message' : message, 'message_date': dates})

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_message  32 non-null     object
 1   message_date  32 non-null     object
dtypes: object(2)
memory usage: 644.0+ bytes

In [11]:
#converting dates into date format from strings (object)

df['message_date']= pd.to_datetime(df['message_date'], format = '%m/%d/%y, %I:%M %p - ')
df.rename(columns={'message_date':'date'}, inplace = 1)

In [12]:
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2024-03-21 17:36:00
1                    Akshit Joshi: <Media omitted>\n 2024-03-21 17:36:00
2                      Ajay Virar: <Media omitted>\n 2024-05-03 11:04:00
3  Ajay Virar: Please send your resume on ajay.vy... 2024-05-03 11:05:00
4                                Akshit Joshi: Yes\n 2024-05-03 11:06:00

In [13]:
df.shape

(32, 2)

In [139]:
users= []
messages = []
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])
df['user']=users
df['message']= messages
df.drop(columns=['user_message'],inplace=True)

In [14]:
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2024-03-21 17:36:00
1                    Akshit Joshi: <Media omitted>\n 2024-03-21 17:36:00
2                      Ajay Virar: <Media omitted>\n 2024-05-03 11:04:00
3  Ajay Virar: Please send your resume on ajay.vy... 2024-05-03 11:05:00
4                                Akshit Joshi: Yes\n 2024-05-03 11:06:00

In [15]:
df['year']= df['date'].dt.year

In [16]:
df.head()

                                        user_message                date  year
0  Messages and calls are end-to-end encrypted. N... 2024-03-21 17:36:00  2024
1                    Akshit Joshi: <Media omitted>\n 2024-03-21 17:36:00  2024
2                      Ajay Virar: <Media omitted>\n 2024-05-03 11:04:00  2024
3  Ajay Virar: Please send your resume on ajay.vy... 2024-05-03 11:05:00  2024
4                                Akshit Joshi: Yes\n 2024-05-03 11:06:00  2024

In [17]:
df['month']=df['date'].dt.month_name()

In [18]:
df.head()

,user_message,date,year,month
0,Messages and calls are end-to-end encrypted. N...,2024-03-21 17:36:00,2024,March
1,Akshit Joshi: <Media omitted>\n,2024-03-21 17:36:00,2024,March
2,Ajay Virar: <Media omitted>\n,2024-05-03 11:04:00,2024,May
3,Ajay Virar: Please send your resume on ajay.vy...,2024-05-03 11:05:00,2024,May
4,Akshit Joshi: Yes\n,2024-05-03 11:06:00,2024,May

In [19]:
df['day']=df['date'].dt.day
df['hour']=df['date'].dt.hour
df['minute']=df['date'].dt.minute

In [20]:
df.head()

,user_message,date,year,month,day,hour,minute
0,Messages and calls are end-to-end encrypted. N...,2024-03-21 17:36:00,2024,March,21,17,36
1,Akshit Joshi: <Media omitted>\n,2024-03-21 17:36:00,2024,March,21,17,36
2,Ajay Virar: <Media omitted>\n,2024-05-03 11:04:00,2024,May,3,11,4
3,Ajay Virar: Please send your resume on ajay.vy...,2024-05-03 11:05:00,2024,May,3,11,5
4,Akshit Joshi: Yes\n,2024-05-03 11:06:00,2024,May,3,11,6

In [21]:
each_counts = round((df['user'].value_counts()/df.shape[0])*100,2).reset_index().rename(columns={'user':'name', 'count':'percent'})
each_counts

KeyError: 'user'

In [22]:
newdf = df[df['message'] != '<Media omitted>\n']

KeyError: 'message'

In [150]:
newdf

,date,user,message,year,month,day,hour,minute
0,2024-03-21 17:36:00,group_notification,Messages and calls are end-to-end encrypted. N...,2024,March,21,17,36
3,2024-05-03 11:05:00,Ajay Virar,Please send your resume on ajay.vyas1@gds.ey c...,2024,May,3,11,5
4,2024-05-03 11:06:00,Akshit Joshi,Yes\n,2024,May,3,11,6
5,2024-05-03 11:06:00,Akshit Joshi,Okay\n,2024,May,3,11,6
6,2024-05-03 11:06:00,Ajay Virar,Good please send resume will refer\n,2024,May,3,11,6
7,2024-05-03 11:07:00,Akshit Joshi,Okay\n,2024,May,3,11,7
8,2024-05-03 11:11:00,Akshit Joshi,Address not found!\n,2024,May,3,11,11
9,2024-05-03 11:12:00,Akshit Joshi,Is it ajay.vyas1@gds.ey.com?\n,2024,May,3,11,12
10,2024-05-03 11:12:00,Ajay Virar,Yes\n,2024,May,3,11,12
11,2024-05-03 11:12:00,Akshit Joshi,Okay\n,2024,May,3,11,12
12,2024-05-03 11:15:00,Akshit Joshi,I have sent the mail\n,2024,May,3,11,15
13,2024-05-03 11:22:00,Ajay Virar,Received\n,2024,May,3,11,22
14,2024-05-03 11:22:00,Akshit Joshi,Okay\n,2024,May,3,11,22
15,2024-05-03 11:23:00,Ajay Virar,Will refer will use emailid and mobile number ...,2024,May,3,11,23
16,2024-05-03 11:24:00,Akshit Joshi,Okay\n,2024,May,3,11,24
17,2024-05-03 11:24:00,Akshit Joshi,Both are active\n,2024,May,3,11,24
18,2024-05-03 11:37:00,Ajay Virar,Ok\n,2024,May,3,11,37
19,2024-05-03 12:12:00,Ajay Virar,Did you received any email from ey\n,2024,May,3,12,12
20,2024-05-03 12:12:00,Ajay Virar,?\n,2024,May,3,12,12
21,2024-05-03 12:15:00,Akshit Joshi,Yes\n,2024,May,3,12,15
22,2024-05-03 12:19:00,Akshit Joshi,I have given both of the concern\n,2024,May,3,12,19
23,2024-05-03 12:41:00,Ajay Virar,Ok\n,2024,May,3,12,41
24,2024-05-05 14:20:00,Ajay Virar,check JP morgan has some openings check if tha...,2024,May,5,14,20
25,2024-05-05 16:48:00,Akshit Joshi,Okay\n,2024,May,5,16,48
26,2024-05-05 16:53:00,Akshit Joshi,I visited this but freshers mate Indian applic...,2024,May,5,16,53
27,2024-05-05 16:54:00,Akshit Joshi,And any update regards to this?\n,2024,May,5,16,54
28,2024-05-05 16:56:00,Ajay Virar,Ok\n,2024,May,5,16,56
29,2024-05-05 16:57:00,Ajay Virar,I have applied if profile is matching than you...,2024,May,5,16,57
30,2024-05-05 16:57:00,Akshit Joshi,Okay\n,2024,May,5,16,57
31,2024-05-05 16:57:00,Akshit Joshi,Thanks ☺️\n,2024,May,5,16,57

In [151]:
df

,date,user,message,year,month,day,hour,minute
0,2024-03-21 17:36:00,group_notification,Messages and calls are end-to-end encrypted. N...,2024,March,21,17,36
1,2024-03-21 17:36:00,Akshit Joshi,<Media omitted>\n,2024,March,21,17,36
2,2024-05-03 11:04:00,Ajay Virar,<Media omitted>\n,2024,May,3,11,4
3,2024-05-03 11:05:00,Ajay Virar,Please send your resume on ajay.vyas1@gds.ey c...,2024,May,3,11,5
4,2024-05-03 11:06:00,Akshit Joshi,Yes\n,2024,May,3,11,6
5,2024-05-03 11:06:00,Akshit Joshi,Okay\n,2024,May,3,11,6
6,2024-05-03 11:06:00,Ajay Virar,Good please send resume will refer\n,2024,May,3,11,6
7,2024-05-03 11:07:00,Akshit Joshi,Okay\n,2024,May,3,11,7
8,2024-05-03 11:11:00,Akshit Joshi,Address not found!\n,2024,May,3,11,11
9,2024-05-03 11:12:00,Akshit Joshi,Is it ajay.vyas1@gds.ey.com?\n,2024,May,3,11,12
10,2024-05-03 11:12:00,Ajay Virar,Yes\n,2024,May,3,11,12
11,2024-05-03 11:12:00,Akshit Joshi,Okay\n,2024,May,3,11,12
12,2024-05-03 11:15:00,Akshit Joshi,I have sent the mail\n,2024,May,3,11,15
13,2024-05-03 11:22:00,Ajay Virar,Received\n,2024,May,3,11,22
14,2024-05-03 11:22:00,Akshit Joshi,Okay\n,2024,May,3,11,22
15,2024-05-03 11:23:00,Ajay Virar,Will refer will use emailid and mobile number ...,2024,May,3,11,23
16,2024-05-03 11:24:00,Akshit Joshi,Okay\n,2024,May,3,11,24
17,2024-05-03 11:24:00,Akshit Joshi,Both are active\n,2024,May,3,11,24
18,2024-05-03 11:37:00,Ajay Virar,Ok\n,2024,May,3,11,37
19,2024-05-03 12:12:00,Ajay Virar,Did you received any email from ey\n,2024,May,3,12,12
20,2024-05-03 12:12:00,Ajay Virar,?\n,2024,May,3,12,12
21,2024-05-03 12:15:00,Akshit Joshi,Yes\n,2024,May,3,12,15
22,2024-05-03 12:19:00,Akshit Joshi,I have given both of the concern\n,2024,May,3,12,19
23,2024-05-03 12:41:00,Ajay Virar,Ok\n,2024,May,3,12,41
24,2024-05-05 14:20:00,Ajay Virar,check JP morgan has some openings check if tha...,2024,May,5,14,20
25,2024-05-05 16:48:00,Akshit Joshi,Okay\n,2024,May,5,16,48
26,2024-05-05 16:53:00,Akshit Joshi,I visited this but freshers mate Indian applic...,2024,May,5,16,53
27,2024-05-05 16:54:00,Akshit Joshi,And any update regards to this?\n,2024,May,5,16,54
28,2024-05-05 16:56:00,Ajay Virar,Ok\n,2024,May,5,16,56
29,2024-05-05 16:57:00,Ajay Virar,I have applied if profile is matching than you...,2024,May,5,16,57
30,2024-05-05 16:57:00,Akshit Joshi,Okay\n,2024,May,5,16,57
31,2024-05-05 16:57:00,Akshit Joshi,Thanks ☺️\n,2024,May,5,16,57

In [161]:
from collections import Counter

def word_counter(user, df):

    words=[]

    if user != 'overall':
        df = df[df['user']==user]


    temp = df[df['user']!='group_notification']
    temp = temp[temp['message'] != '<Media omitted>\n']

    f = open("HinglishStopWordFile\stop_hinglish.txt", 'r')
    stopWords = f.read()
    for msg in temp['message']:
        for word in msg.lower().split():
            if word not in stopWords:
                words.append(word)
        
    

    return pd.DataFrame(Counter(words).most_common(20))

In [162]:
temp = word_counter("overall", df)

In [163]:
temp

                         0  1
0                   resume  3
1                     send  2
2                    refer  2
3                 received  2
4                    check  2
5                     mate  2
6        ajay.vyas1@gds.ey  1
7                  address  1
8                   found!  1
9   ajay.vyas1@gds.ey.com?  1
10                    mail  1
11                 emailid  1
12                  mobile  1
13                  number  1
14                  active  1
15                   email  1
16                 concern  1
17                      jp  1
18                  morgan  1
19                openings  1

In [35]:
df['month_num'] = df['date'].dt.month
timeline = df.groupby(['year', 'month_num','month']).count()['user_message'].reset_index()
time = []
for i in range(timeline.shape[0]):
    time.append(timeline['month'][i] + "-" + str(timeline['year'][i]))

In [37]:
timeline["time"]= time

In [38]:
timeline

   year  month_num  month  user_message        time
0  2024          3  March             2  March-2024
1  2024          5    May            30    May-2024

In [ ]:
plt.plot(timeline['time'], timeline['messeage'])